---
# Example custom values for ONZACK simple-website-monitoring
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: "Europe/Zurich"

# InfluxDB configuration
swmDb:
  authEnabled: true
  influxDbUrl: http://influxdb.example.com
  influxDbPort: 80
  influxDbName: telegraf
  influxDbUser: REDACTED
  influxDbPW: REDATCED
