---
# Example custom values for ONZACK simple-website-monitoring
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: "Europe/Zurich"

swm:
  urls: '["https://www.example.com" "https://test.example.com"]'

# InfluxDB configuration
swmDb:
  influxDbUrl: http://influxdb.example.com
  influxDbName: telegraf
  influxDbUser: REDACTED
  influxDbPW: REDATCED
