{
 "title": "Telegraf: simple-website-monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overall HTTP Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"http_response_code\" AS \"status\" FROM \"telegraf\".\"autogen\".\"http_response\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Result Code Status (single max value)",
   "type": "stat",
   "description": "The Result Code for the Telegraf checks:  \n0 = success  \n1 = response_string_mismatch  \n2 = body_read_error  \n3 = connection_failed  \n4 = timeout  \n5 = dns_error  \n6 = response_status_code_mismatch  \nSee Docs on [GitHub](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_response#result--result_code)  ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  \"result_code\" AS \"result\" FROM \"telegraf\".\"autogen\".\"http_response\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "description": "The HTTP Status Code for all monitored websites.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "HTTP Status Code" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"http_response_code\" AS \"status\" FROM \"telegraf\".\"autogen\".\"http_response\" WHERE $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telegraf Result code",
   "type": "graph",
   "description": "The Result Code for the Telegraf checks:  \n0 = success  \n1 = response_string_mismatch  \n2 = body_read_error  \n3 = connection_failed  \n4 = timeout  \n5 = dns_error  \n6 = response_status_code_mismatch  \nSee Docs on [GitHub](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_response#result--result_code)  ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Telegraf Result code" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"result_code\" AS \"result\" FROM \"telegraf\".\"autogen\".\"http_response\" WHERE $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "description": "The response time in Seconds",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"response_time\" AS \"time\" FROM \"telegraf\".\"autogen\".\"http_response\" WHERE $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Content Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes", "label": "Content Length" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"content_length\" AS \"length\" FROM \"telegraf\".\"autogen\".\"http_response\" WHERE $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}