---
# Default values for ONZACK website
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: "Europe/Zurich"

swm:
  repository: telegraf
  tag: alpine
  pullPolicy: IfNotPresent
  requests:
    memory: 100Mi
    cpu: 150m
  limits:
    memory: 250Gi
    cpu: 500m
  # imagePullSecret is only necessary if you use a Telegraf image from a private registry.  
  imagePullSecret: REDACTED

# InfluxDB configuration
swmDb:
  authEnabled: true
  influxDbUrl: http://influxdb.example.com
  influxDbPort: 80
  influxDbName: telegraf
  influxDbUser: REDACTED
  influxDbPW: REDATCED
