---
# Default values for ONZACK simple-website-monitoring
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: "Europe/Zurich"

swm:
  repository: quay.io/onzack/telegraf-swm
  tag: latest
  pullPolicy: IfNotPresent
  requests:
    memory: 100Mi
    cpu: 150m
  limits:
    memory: 250Gi
    cpu: 500m
  # imagePullSecret is only necessary if you use a Telegraf image from a private registry.
  imagePullSecret: REDACTED
  urls: '"https://www.onzack.com" "https://git.lab.onzack.io" "https://workbench.onzack.com"'

# InfluxDB configuration
swmDb:
  influxDbUrl: http://influxdb.example.com
  influxDbName: telegraf
  influxDbUser: REDACTED
  influxDbPW: REDATCED
