---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-website-monitor
  name: simple-website-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website-monitor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-website-monitor
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      containers:
      - name: simple-website-monitor
        image: "{{ .Values.swm.repository }}:{{ .Values.swm.tag }}"
        imagePullPolicy: {{ .Values.swm.pullPolicy }}
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
             - ALL
        resources:
          requests:
            memory: {{ .Values.swm.requests.memory | quote }}
            cpu: {{ .Values.swm.requests.cpu | quote }}
          limits:
            memory: {{ .Values.swm.limits.memory | quote }}
            cpu: {{ .Values.swm.limits.cpu | quote }}
        env:
          - name: TZ
            value: {{ .Values.timezone | quote }}
          {{- end }}
      {{- if .Values.swmDb.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.swm.imagePullSecret }}
      {{- end }}
