---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: simple-website-monitor
spec:
  podSelector:
    matchLabels:
      app: simple-website-monitor
  policyTypes:
  - Egress
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
